#!/usr/bin/env python3
"""
txn.py — XAIE transaction buffer parser/disassembler

The transaction buffer is the runtime control sequence that the host
sends to the NPU to orchestrate DMA transfers and kernel execution.
It is distinct from the CDO in the xclbin (which initialises the AIE
hardware). Two encodings are seen in the wild:

1. FastFlowLM native npu_seq (npu_instr_utils.hpp cmds2seq/seq2cmds):
   A 4-word device header followed by XAIE_IO_* commands:
     [0] major[7:0] | minor[15:8] | dev_gen[23:16] | rows[31:24]
     [1] cols[7:0]  | mem_tile_rows[15:8]
     [2] instruction count
     [3] total byte size of the stream
   Commands on the wire:
     WRITE(6w)  BLOCKWRITE(12w = shim DMA BD config)  MASKWRITE(7w =
     issue-token)  PREEMPT(1w)  TCT(4w wait-sync)  DDR_PATCH(12w)

2. aiebu DPU ctrltext (post-conversion, what xrt::elf receives):
   shim DMA BDs appear as DMA_BD_FENCE (opcode 0x30) + six WRITEs;
   see find_dma_bd_groups() below.

Opcode reference: FastFlowLM src/include/npu_utils/instr_utils/npu_cmd*.hpp
                  npu_instr_utils.hpp (seq2cmds dispatcher)
                  mlir-aie/lib/Dialect/AIEX/IR/AIEXDialect.cpp
                  mlir-aie/lib/Targets/AIETargetNPU.cpp
"""

from __future__ import annotations
import argparse
import json
import struct
import sys
from dataclasses import dataclass, field
from enum import IntEnum
from pathlib import Path
from typing import Optional


# ── Opcodes ──────────────────────────────────────────────────────────────────

class Op(IntEnum):
    WRITE           = 0x00   # write single 32-bit register
    BLOCKWRITE      = 0x01   # write N consecutive words (for tile PM or DM)
    BLOCKSET        = 0x02   # set N words to a constant value
    MASKWRITE       = 0x03   # read-modify-write with mask  (push queue / issue token)
    MASKPOLL        = 0x04   # poll register until (val & mask) == expected
    NOOP            = 0x05
    PREEMPT         = 0x06
    MASKPOLL_BUSY   = 0x07
    LOADPDI         = 0x08
    LOAD_PM_START   = 0x09
    CREATE_SCRATCH  = 0x0A
    UPDATE_STATE    = 0x0B
    UPDATE_REG      = 0x0C
    UPDATE_SCRATCH  = 0x0D
    SHIMDMA_BD      = 0x0E   # configure a shim DMA buffer descriptor
    SHIMDMA_BUF_BD  = 0x0F   # configure a shim DMA BO buffer descriptor
    # Custom / high-level ops (generated by mlir-aie AIEX passes)
    TCT             = 0x80   # trigger completion token
    DDR_PATCH       = 0x81   # patch a BD address field with a DDR BO address
    READ_REGS       = 0x82
    RECORD_TIMER    = 0x83
    MERGE_SYNC      = 0x84


OP_NAMES = {int(o): o.name for o in Op}
# Empirically identified opcodes not in the XAIE2 standard set:
OP_NAMES[0x30] = "DMA_BD_FENCE"   # 1-word DMA transaction fence; precedes each BD setup group


# ── Address helpers ───────────────────────────────────────────────────────────

BD_COL_SHIFT = 25
BD_ROW_SHIFT = 20
BD_COL_MASK  = 0x7F
BD_ROW_MASK  = 0x1F

def decode_addr(word: int) -> tuple[int, int, int]:
    """Return (col, row, reg_offset) from an AIE tile address word."""
    col = (word >> BD_COL_SHIFT) & BD_COL_MASK
    row = (word >> BD_ROW_SHIFT) & BD_ROW_MASK
    reg = word & 0xFFFFF
    return col, row, reg

QUEUE_REGS = {
    # (S2MM=0/MM2S=1, channel) → queue register name
    (0, 0): "DMA_S2MM_0_TASK_QUEUE",
    (0, 1): "DMA_S2MM_1_TASK_QUEUE",
    (1, 0): "DMA_MM2S_0_TASK_QUEUE",
    (1, 1): "DMA_MM2S_1_TASK_QUEUE",
}

SHIM_BD_BASE = 0x1D000      # shim DMA BD register base offset


# ── Decoded instruction dataclasses ─────────────────────────────────────────

@dataclass
class BufferHeader:
    """4-word device header of a FastFlowLM native npu_seq stream."""
    major: int
    minor: int
    dev_gen: int
    rows: int
    cols: int
    mem_tile_rows: int
    instr_count: int
    total_bytes: int

    def describe(self) -> str:
        return (f"NPU{self.npu_name()}  {self.cols} cols × {self.rows} rows  "
                f"({self.mem_tile_rows} mem-tile row)  "
                f"{self.instr_count} instructions, "
                f"{self.total_bytes} bytes")

    def npu_name(self) -> str:
        return f"{self.major}.{self.minor} gen{self.dev_gen}"


@dataclass
class Instr:
    offset: int       # byte offset in stream
    opcode: int
    words: list[int]  # raw words

    @property
    def op_name(self) -> str:
        return OP_NAMES.get(self.opcode, f"UNK_0x{self.opcode:02x}")

    def describe(self) -> str:
        return f"[0x{self.offset:06x}] {self.op_name}"


@dataclass
class WriteInstr(Instr):
    col: int
    row: int
    reg: int
    value: int
    is_push_queue: bool = False
    direction: str = ""     # "S2MM" or "MM2S"
    channel: int = 0
    bd_id: int = 0
    repeat: int = 0
    issue_token: bool = False

    def describe(self) -> str:
        if self.is_push_queue:
            dir_sym = "→" if self.direction == "MM2S" else "←"
            tok = " +TOKEN" if self.issue_token else ""
            return (f"[0x{self.offset:06x}] PUSH_QUEUE  tile({self.col},{self.row})  "
                    f"{self.direction}_ch{self.channel}  bd={self.bd_id}  "
                    f"repeat={self.repeat}{tok}")
        return (f"[0x{self.offset:06x}] WRITE       tile({self.col},{self.row})  "
                f"reg=0x{self.reg:05x}  val=0x{self.value:08x}")


@dataclass
class BlockWriteInstr(Instr):
    col: int
    row: int
    reg: int
    count: int        # number of 32-bit words
    payload: list[int] = field(repr=False, default_factory=list)

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] BLOCKWRITE  tile({self.col},{self.row})  "
                f"reg=0x{self.reg:05x}  words={self.count}")


@dataclass
class MaskWriteInstr(Instr):
    col: int
    row: int
    reg: int
    value: int
    mask: int
    direction: str
    channel: int
    pkt_id: int

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] ISSUE_TOKEN tile({self.col},{self.row})  "
                f"{self.direction}_ch{self.channel}  pkt_id=0x{self.pkt_id:x}  "
                f"mask=0x{self.mask:08x}")


@dataclass
class DdrPatchInstr(Instr):
    col: int
    row: int
    bd_id: int
    arg_idx: int
    arg_offset: int

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] DDR_PATCH   tile({self.col},{self.row})  "
                f"bd={self.bd_id}  arg[{self.arg_idx}]+0x{self.arg_offset:x}")


@dataclass
class ShimDmaBdInstr(Instr):
    col: int
    row: int
    bd_id: int
    buf_len: int        # in 32-bit words
    buf_offset: int
    direction: str      # filled from the queue-push WRITE that kicks this BD
    # addressing / tiling
    dim0_size: int = 0
    dim0_stride: int = 0
    dim1_size: int = 0
    dim1_stride: int = 0
    dim2_size: int = 0
    dim2_stride: int = 0
    # iteration dimension (stored size-1 on the wire)
    iter_size: int = 0
    iter_stride: int = 0
    # QoS: AxCache field of the D2 word
    axcache: int = 0
    # chaining
    next_bd: int = 0
    use_next_bd: bool = False
    valid: bool = True
    # packet switching
    pkt_enable: bool = False
    pkt_id: int = 0
    pkt_type: int = 0
    repeat: int = 0
    issue_token: bool = False

    def describe(self) -> str:
        dims = f"  [{self.buf_len}w off={self.buf_offset:x}]"
        tiling = ""
        if self.dim0_size:
            tiling = f"  d0={self.dim0_size}×{self.dim0_stride}"
        if self.dim1_size:
            tiling += f"  d1={self.dim1_size}×{self.dim1_stride}"
        if self.iter_size > 1:
            tiling += f"  iter={self.iter_size}×{self.iter_stride}"
        chain = f"  →bd{self.next_bd}" if self.use_next_bd else ""
        return (f"[0x{self.offset:06x}] SHIMDMA_BD  tile({self.col},{self.row})  "
                f"bd={self.bd_id}{dims}{tiling}{chain}")


@dataclass
class WaitSyncInstr(Instr):
    """TCT custom op — wait for a completion token on a shim DMA channel."""
    col: int
    row: int
    channel: int
    direction: str

    def describe(self) -> str:
        return (f"[0x{self.offset:06x}] WAIT_SYNC   tile({self.col},{self.row})  "
                f"{self.direction}_ch{self.channel}")


@dataclass
class PreemptInstr(Instr):
    level: int = 0

    def describe(self) -> str:
        return f"[0x{self.offset:06x}] PREEMPT     level={self.level}"


# ── Parser ───────────────────────────────────────────────────────────────────

class TxnParser:
    """Parse a raw XAIE transaction buffer (list of uint32 words or bytes).

    header=True (default) consumes the 4-word FastFlowLM device header
    first; pass header=False for bare command streams.
    """

    def __init__(self, words: list[int], header: bool = True):
        self.words = words
        self.pos = 0
        self.instrs: list[Instr] = []
        self.header: Optional[BufferHeader] = None
        self.want_header = header

    # --- helpers ---

    def _peek(self, n: int = 1) -> list[int]:
        return self.words[self.pos: self.pos + n]

    def _read(self, n: int) -> list[int]:
        chunk = self.words[self.pos: self.pos + n]
        self.pos += n
        return chunk

    def _parse_header(self):
        if len(self.words) < 4:
            return
        w = self._read(4)
        self.header = BufferHeader(
            major=w[0] & 0xFF,
            minor=(w[0] >> 8) & 0xFF,
            dev_gen=(w[0] >> 16) & 0xFF,
            rows=(w[0] >> 24) & 0xFF,
            cols=w[1] & 0xFF,
            mem_tile_rows=(w[1] >> 8) & 0xFF,
            instr_count=w[2],
            total_bytes=w[3],
        )

    # --- main loop ---

    def parse(self) -> list[Instr]:
        self.instrs = []
        if self.want_header:
            self._parse_header()
        while self.pos < len(self.words):
            byte_off = self.pos * 4
            opcode = self.words[self.pos] & 0xFF

            if opcode == Op.WRITE:
                self._parse_write(byte_off)
            elif opcode == Op.BLOCKWRITE:
                self._parse_blockwrite(byte_off)
            elif opcode == Op.MASKWRITE:
                self._parse_maskwrite(byte_off)
            elif opcode == Op.DDR_PATCH:
                self._parse_ddr_patch(byte_off)
            elif opcode == Op.SHIMDMA_BD:
                self._parse_shimdma_bd(byte_off)
            elif opcode == Op.TCT:
                self._parse_tct(byte_off)
            elif opcode == Op.PREEMPT:
                w = self._read(1)
                level = (w[0] >> 8) & 0x3
                self.instrs.append(PreemptInstr(
                    offset=byte_off, opcode=Op.PREEMPT, words=w, level=level))
            elif opcode == Op.NOOP:
                w = self._read(1)
                self.instrs.append(Instr(byte_off, opcode, w))
            else:
                # Unknown opcodes — use bits[31:24] of op word as instruction
                # size (in words) when available; fall back to skip-1.
                maybe_size = (self.words[self.pos] >> 24) & 0xFF
                if 1 < maybe_size <= 64:
                    n = maybe_size
                elif self.pos + 1 < len(self.words):
                    raw_size = (self.words[self.pos + 1] >> 2) & 0x3FFFFF
                    n = raw_size if 1 < raw_size <= 64 else 1
                else:
                    n = 1
                n = min(n, len(self.words) - self.pos)
                w = self._read(n)
                self.instrs.append(Instr(byte_off, opcode, w))
        return self.instrs

    def _parse_write(self, byte_off: int):
        # 6 words: [opcode][unused][addr_word][unused][value][op_size<<2]
        # Guard: if < 6 words remain, read what we can and emit unknown
        if self.pos + 6 > len(self.words):
            w = self._read(len(self.words) - self.pos)
            self.instrs.append(Instr(byte_off, Op.WRITE, w))
            return
        w = self._read(6)
        col, row, reg = decode_addr(w[2])
        value = w[4]
        is_queue = (reg & 0x1FE00) == 0x1D200
        instr = WriteInstr(
            offset=byte_off, opcode=Op.WRITE, words=w,
            col=col, row=row, reg=reg, value=value,
            is_push_queue=is_queue,
        )
        if is_queue:
            instr.direction = "MM2S" if (reg & 0x10) else "S2MM"
            instr.channel = (reg >> 3) & 0x1
            instr.bd_id = value & 0xF
            instr.repeat = (value >> 16) & 0xFF
            instr.issue_token = bool(value >> 31)
        self.instrs.append(instr)

    def _parse_blockwrite(self, byte_off: int):
        # FastFlowLM emits BLOCKWRITE exclusively as the 12-word shim DMA BD
        # config (npu_cmd_write_dma.hpp npu_dma_block_cmd::to_npu):
        #   [0]=op [1]=0 [2]=loc(row|col|bd<<5|0x1D000) [3]=op_size*4
        #   [4]=buf_len [5]=buf_off [6]=pkt [7]=d0 [8]=burst|d1
        #   [9]=cache|d2_stride [10]=(iter_size-1)|iter_stride-1
        #   [11]=next_bd|use_next|valid|locks
        if self.pos + 12 > len(self.words):
            w = self._read(len(self.words) - self.pos)
            self.instrs.append(Instr(byte_off, Op.BLOCKWRITE, w))
            return
        w = self._read(12)
        col, row, reg = decode_addr(w[2])
        bd_id = (w[2] >> 5) & 0xF

        buf_len = w[4]
        buf_offset = w[5]
        pkt_enable = bool((w[6] >> 30) & 1)
        pkt_id = (w[6] >> 19) & 0x1F
        pkt_type = (w[6] >> 16) & 0x7
        # d0 word == 0 marks a linear (untiled) transfer; strides are stored -1
        linear = w[7] == 0
        dim0_size = 0 if linear else (w[7] >> 20) & 0x3FF
        dim0_stride = 0 if linear else (w[7] & 0xFFFFF) + 1
        dim1_size = (w[8] >> 20) & 0x3FF
        dim1_stride = ((w[8] & 0xFFFFF) + 1) if dim1_size else 0
        axcache = (w[9] >> 24) & 0xF
        dim2_stride = ((w[9] & 0xFFFFF) + 1) if (w[9] & 0xFFFFF) else 0
        iter_size = ((w[10] >> 20) & 0x3FF) + 1
        iter_stride = (w[10] & 0xFFFFF) + 1
        next_bd = (w[11] >> 27) & 0xF
        use_next = bool((w[11] >> 26) & 1)
        valid = bool((w[11] >> 25) & 1)

        if SHIM_BD_BASE <= reg < SHIM_BD_BASE + 0x200:
            self.instrs.append(ShimDmaBdInstr(
                offset=byte_off, opcode=Op.BLOCKWRITE, words=w,
                col=col, row=row, bd_id=bd_id,
                buf_len=buf_len, buf_offset=buf_offset,
                direction="",     # decided by the queue-push WRITE that kicks it
                dim0_size=dim0_size, dim0_stride=dim0_stride,
                dim1_size=dim1_size, dim1_stride=dim1_stride,
                dim2_size=0, dim2_stride=dim2_stride,
                next_bd=next_bd, use_next_bd=use_next, valid=valid,
                pkt_enable=pkt_enable, pkt_id=pkt_id, pkt_type=pkt_type,
                axcache=axcache, iter_size=iter_size, iter_stride=iter_stride,
            ))
        else:
            # Non-BD block writes don't occur in FLM streams; keep the raw
            # words for inspection.
            self.instrs.append(BlockWriteInstr(
                offset=byte_off, opcode=Op.BLOCKWRITE, words=w,
                col=col, row=row, reg=reg, count=len(w) - 4,
                payload=w[4:],
            ))

    def _parse_tct(self, byte_off: int):
        # 4-word wait-sync (npu_cmd_wait.hpp npu_wait_cmd::to_npu):
        #   [0]=op [1]=op_size<<2 [2]=row<<8|col<<16|dir_bit0
        #   [3]=channel<<24 | 0x10100
        w = self._read(4)
        row = (w[2] >> 8) & 0xFF
        col = (w[2] >> 16) & 0xFF
        direction = "MM2S" if (w[2] & 0x1) else "S2MM"
        channel = (w[3] >> 24) & 0xFF
        self.instrs.append(WaitSyncInstr(
            offset=byte_off, opcode=Op.TCT, words=w,
            col=col, row=row, channel=channel, direction=direction,
        ))

    def _parse_maskwrite(self, byte_off: int):
        # 7 words: [op][unused][addr][unused][value][mask][op_size]
        w = self._read(7)
        col, row, reg = decode_addr(w[2])
        value = w[4]
        mask = w[5]
        direction = "MM2S" if (reg & 0x10) else "S2MM"
        channel = (reg >> 3) & 0x1
        pkt_id = (value >> 8) & 0xFFFFFF
        self.instrs.append(MaskWriteInstr(
            offset=byte_off, opcode=Op.MASKWRITE, words=w,
            col=col, row=row, reg=reg, value=value, mask=mask,
            direction=direction, channel=channel, pkt_id=pkt_id,
        ))

    def _parse_ddr_patch(self, byte_off: int):
        # 12 words: [op][size<<2][0][0][0][0][bd_reg][0][arg_idx][0][arg_off][0]
        w = self._read(12)
        bd_reg = w[6]
        col = (bd_reg >> BD_COL_SHIFT) & BD_COL_MASK
        row = (bd_reg >> BD_ROW_SHIFT) & BD_ROW_MASK
        bd_id = ((bd_reg - 0x04) >> 5) & 0x1F
        arg_idx = w[8]
        arg_offset = w[10]
        self.instrs.append(DdrPatchInstr(
            offset=byte_off, opcode=Op.DDR_PATCH, words=w,
            col=col, row=row, bd_id=bd_id,
            arg_idx=arg_idx, arg_offset=arg_offset,
        ))

    def _parse_shimdma_bd(self, byte_off: int):
        # 12 words per BD configure command — from npu_cmd_write_dma.hpp
        w = self._read(12)
        # word[0] = (is_bd<<12)|(col<<25)|(row<<20)|(bd_id<<5) | Op
        op_word = w[0]
        col = (op_word >> BD_COL_SHIFT) & BD_COL_MASK
        row = (op_word >> BD_ROW_SHIFT) & BD_ROW_MASK
        bd_id = (op_word >> 5) & 0xF
        # word[1] = buffer_length
        buf_len = w[1]
        # word[2] = buffer_offset
        buf_offset = w[2]
        # word[3] = packet/enable flags
        pkt_enable = bool((w[3] >> 30) & 1)
        pkt_id = (w[3] >> 19) & 0x1F
        pkt_type = (w[3] >> 16) & 0x7
        # word[4] = dim0 (size<<20 | stride)
        dim0_stride = w[4] & 0xFFFFF
        dim0_size = (w[4] >> 20) & 0x3FF
        # word[5] = dim1
        dim1_stride = w[5] & 0xFFFFF
        dim1_size = (w[5] >> 20) & 0x3FF
        # word[6] = iter/dim2
        iter_stride = w[6] & 0xFFFFF
        iter_size = (w[6] >> 20) & 0x3FF
        # word[7] = dim2
        dim2_stride = w[7] & 0xFFFFF
        dim2_size = (w[7] >> 20) & 0x3FF
        # word[8] = lock acquire/release
        # word[9] = next bd / valid
        next_bd = (w[9] >> 27) & 0xF
        use_next = bool((w[9] >> 26) & 1)
        valid = bool((w[9] >> 25) & 1)
        # word[10] = repeat/token
        repeat = (w[10] >> 16) & 0xFF if len(w) > 10 else 0
        issue_token = bool(w[10] >> 31) if len(w) > 10 else False

        self.instrs.append(ShimDmaBdInstr(
            offset=byte_off, opcode=Op.SHIMDMA_BD, words=w,
            col=col, row=row, bd_id=bd_id,
            buf_len=buf_len, buf_offset=buf_offset,
            dim0_size=dim0_size, dim0_stride=dim0_stride,
            dim1_size=dim1_size, dim1_stride=dim1_stride,
            dim2_size=dim2_size, dim2_stride=dim2_stride,
            next_bd=next_bd, use_next_bd=use_next, valid=valid,
            pkt_enable=pkt_enable, pkt_id=pkt_id, pkt_type=pkt_type,
            repeat=repeat, issue_token=issue_token,
        ))


def from_bytes(data: bytes, header: bool = True) -> list[Instr]:
    """Parse a raw transaction buffer from bytes."""
    words = list(struct.unpack_from(f"<{len(data)//4}I", data))
    return TxnParser(words, header=header).parse()


def from_words(words: list[int], header: bool = True) -> list[Instr]:
    return TxnParser(words, header=header).parse()


def describe_all(instrs: list[Instr]) -> str:
    return "\n".join(i.describe() for i in instrs)


# ── DMA topology extractor ────────────────────────────────────────────────────

@dataclass
class DmaTransfer:
    direction: str     # "H2D" (host-to-device) / "D2H" / "?" if unknown
    arg_idx: int       # which kernel buffer arg
    arg_offset: int
    col: int
    bd_id: int
    channel: int       # shim DMA channel, -1 if unknown
    buf_len: int       # words
    strides: list[tuple[int, int]]  # [(size,stride), ...]

    def describe(self) -> str:
        arrow = {"H2D": "→NPU", "D2H": "←NPU"}.get(self.direction, "?")
        dims = "  ".join(f"[{s}×{st}]" for s, st in self.strides if s)
        ch = f"_ch{self.channel}" if self.channel >= 0 else ""
        return (f"arg[{self.arg_idx}]+{self.arg_offset:#x}  {arrow}  "
                f"col={self.col}{ch} bd={self.bd_id}  "
                f"len={self.buf_len*4}B  {dims}")


# MM2S reads DDR into the AIE array (host→device); S2MM streams out to DDR
# (device→host). Queue-push WRITEs carry the definitive per-transfer direction.
_QUEUE_DIRECTION_MAP = {"MM2S": "H2D", "S2MM": "D2H"}

# How far past a DDR_PATCH to look for the matching queue-push WRITE before
# giving up on direction inference. BD setup groups are short; this is ample.
_PUSH_QUEUE_SEARCH_WINDOW = 64


def _find_queue_push(instrs: list[Instr], patch_idx: int,
                     col: int, bd_id: int) -> Optional[WriteInstr]:
    """Locate the first queue-push WRITE after *patch_idx* that pushes the
    same shim-DMA BD the patch belongs to."""
    limit = min(len(instrs), patch_idx + 1 + _PUSH_QUEUE_SEARCH_WINDOW)
    fallback: Optional[WriteInstr] = None
    for j in range(patch_idx + 1, limit):
        instr = instrs[j]
        if not isinstance(instr, WriteInstr) or not instr.is_push_queue:
            continue
        if instr.col != col:
            continue
        if instr.bd_id == bd_id:
            return instr
        # Same column but different BD — remember it as a weak fallback only
        # if no exact match shows up soon (some flows reuse one push for a
        # chain of BDs via next_bd chaining).
        if fallback is None:
            fallback = instr
    return fallback


def extract_dma_topology(instrs: list[Instr]) -> list[DmaTransfer]:
    """
    Correlate DDR_PATCH instructions with SHIMDMA_BD descriptors to produce
    a human-readable table of host↔NPU DMA transfers.

    Transfer direction comes from the task-queue push WRITE that kicks off
    each BD: its decoded queue register gives MM2S (host→device) or S2MM
    (device→host). Transfers with no nearby queue push keep direction "?".
    """
    # Index BDs by (col, row, bd_id)
    bds: dict[tuple, ShimDmaBdInstr] = {}
    for i in instrs:
        if isinstance(i, ShimDmaBdInstr):
            bds[(i.col, i.row, i.bd_id)] = i

    transfers: list[DmaTransfer] = []
    for idx, i in enumerate(instrs):
        if not isinstance(i, DdrPatchInstr):
            continue
        bd = bds.get((i.col, i.row, i.bd_id))
        if bd is None:
            continue

        direction, channel = "?", -1
        push = _find_queue_push(instrs, idx, i.col, i.bd_id)
        if push is None and bd.use_next_bd:
            # Chained BDs are kicked by a single push of the head BD.
            push = _find_queue_push(instrs, idx, i.col, bd.next_bd)
        if push is not None:
            direction = _QUEUE_DIRECTION_MAP.get(push.direction, "?")
            channel = push.channel

        strides = [
            (bd.dim0_size, bd.dim0_stride),
            (bd.dim1_size, bd.dim1_stride),
            (bd.dim2_size, bd.dim2_stride),
        ]
        transfers.append(DmaTransfer(
            direction=direction,
            arg_idx=i.arg_idx,
            arg_offset=i.arg_offset,
            col=i.col,
            channel=channel,
            bd_id=i.bd_id,
            buf_len=bd.buf_len,
            strides=strides,
        ))
    return transfers


# ── DMA BD group extractor ────────────────────────────────────────────────────
#
# In the aiebu DPU ctrltext, each shim DMA BD is programmed by a "BD group":
#   DMA_BD_FENCE (1 word, opcode 0x30) followed by exactly 6 WRITEs (36 words)
#
# The 6 WRITEs are:
#   [0] DDR addr_low placeholder  — RELA type-5 patches w[0] with actual DDR addr
#       reg=0x0 (decoded from w[2]=0), w[4]=BD_ctrl_word
#   [1] DMA size/config           — reg=0x81 (or col-encoded), val=0
#   [2] BD.word1 (addr_high)      — reg=BD_base+4|col_bits, val=addr_hi (DDR bits[39:32])
#   [3] Queue kickoff (indirect)  — reg=0x3, val=queue_register_address
#   [4] Status clear              — reg=0x1c, val=0
#   [5] DMA enable/control        — reg=0x18, val=0
#
# The BD and column are identified from WRITE[2]'s register address.
# RELA r_offset points to the START of WRITE[0] (i.e., its w[0] = DDR addr_low slot).

# Shim DMA channel queue registers (tile-local offsets, col bits added at runtime)
_SHIM_QUEUE_REGS: dict[int, tuple[str, int]] = {
    0x1d200: ("S2MM", 0), 0x1d204: ("S2MM", 0),
    0x1d208: ("S2MM", 1), 0x1d20c: ("S2MM", 1),
    0x1d210: ("MM2S", 0), 0x1d214: ("MM2S", 0),
    0x1d218: ("MM2S", 1), 0x1d21c: ("MM2S", 1),
}


@dataclass
class DmaBdGroup:
    """One DMA BD programming group decoded from a DMA_BD_FENCE + 6 WRITEs sequence."""
    fence_instr_idx: int    # index of the DMA_BD_FENCE instruction
    addr_write_idx: int     # index of WRITE[0] (the one whose w[0] is RELA-patched)
    ddr_addr_lo_placeholder: int  # w[0] before RELA patching (e.g. 0x00010000)
    bd_ctrl: int            # BD control word from WRITE[0].w[4]
    col: int                # shim column (from WRITE[2]'s register address bits[31:25])
    bd_id: int              # BD index within the column's shim DMA (0..15)
    addr_hi: int            # DDR addr bits[39:32] (from WRITE[2].value)
    direction: str          # "MM2S" or "S2MM" or "?"
    channel: int            # DMA channel index (0 or 1), -1 if unknown

    def describe(self) -> str:
        dir_arrow = "→NPU" if self.direction == "MM2S" else "←NPU"
        return (f"DMA_BD_GROUP  col={self.col}  bd={self.bd_id}  "
                f"{self.direction}_ch{self.channel}  {dir_arrow}  "
                f"ddr_hi={self.addr_hi}  ctrl=0x{self.bd_ctrl:08x}")


def find_dma_bd_groups(instrs: list[Instr]) -> list[DmaBdGroup]:
    """Scan the instruction stream for DMA_BD_FENCE + 6 WRITEs patterns.

    Each such group programs one shim DMA BD with a DDR buffer address.
    The first WRITE's w[0] is the RELA relocation target (DDR addr_low placeholder).
    Returns one DmaBdGroup per fence found.
    """
    groups: list[DmaBdGroup] = []
    for fi, instr in enumerate(instrs):
        if instr.opcode != 0x30:
            continue
        # Need at least 6 more instructions
        if fi + 6 >= len(instrs):
            continue
        # WRITE[0]: DDR addr_lo write — reg must be 0, w[0] is RELA target
        addr_w = instrs[fi + 1]
        if not isinstance(addr_w, WriteInstr) or addr_w.reg != 0:
            continue
        placeholder = addr_w.words[0] if addr_w.words else 0
        bd_ctrl = addr_w.words[4] if len(addr_w.words) > 4 else 0

        # WRITE[2]: BD.word1 → col and bd_id
        bd_word1_w = instrs[fi + 3]
        col, bd_id, addr_hi = -1, -1, -1
        if isinstance(bd_word1_w, WriteInstr):
            r = bd_word1_w.reg
            if 0x1d004 <= r <= 0x1d1fc and (r - 0x1d004) % 0x20 == 0:
                col = bd_word1_w.col
                bd_id = (r - 0x1d004) // 0x20
                addr_hi = bd_word1_w.value

        # WRITE[3]: queue kickoff → direction and channel (value encodes queue reg)
        queue_w = instrs[fi + 4]
        direction, channel = "?", -1
        if isinstance(queue_w, WriteInstr):
            qv = queue_w.value & 0x1FFFFF  # strip column bits
            if qv in _SHIM_QUEUE_REGS:
                direction, channel = _SHIM_QUEUE_REGS[qv]

        groups.append(DmaBdGroup(
            fence_instr_idx=fi,
            addr_write_idx=fi + 1,
            ddr_addr_lo_placeholder=placeholder,
            bd_ctrl=bd_ctrl,
            col=col,
            bd_id=bd_id,
            addr_hi=addr_hi,
            direction=direction,
            channel=channel,
        ))
    return groups


# ── CLI ───────────────────────────────────────────────────────────────────────

def _instr_to_dict(i: Instr) -> dict:
    d = {"offset": i.offset, "opcode": i.opcode, "op": i.op_name,
         "raw_words": [f"0x{w:08x}" for w in i.words]}
    if isinstance(i, WriteInstr):
        d.update(col=i.col, row=i.row, reg=f"0x{i.reg:05x}",
                 value=f"0x{i.value:08x}")
        if i.is_push_queue:
            d.update(push_queue=True, direction=i.direction,
                     channel=i.channel, bd_id=i.bd_id, repeat=i.repeat,
                     issue_token=i.issue_token)
    elif isinstance(i, BlockWriteInstr):
        d.update(col=i.col, row=i.row, reg=f"0x{i.reg:05x}", count=i.count)
    elif isinstance(i, MaskWriteInstr):
        d.update(col=i.col, row=i.row, reg=f"0x{i.reg:05x}",
                 value=f"0x{i.value:08x}", mask=f"0x{i.mask:08x}",
                 direction=i.direction, channel=i.channel, pkt_id=i.pkt_id)
    elif isinstance(i, DdrPatchInstr):
        d.update(col=i.col, row=i.row, bd_id=i.bd_id, arg_idx=i.arg_idx,
                 arg_offset=i.arg_offset)
    elif isinstance(i, ShimDmaBdInstr):
        d.update(col=i.col, row=i.row, bd_id=i.bd_id,
                 buf_len_words=i.buf_len, buf_offset=i.buf_offset,
                 dims=[(i.dim0_size, i.dim0_stride), (i.dim1_size, i.dim1_stride),
                       (i.dim2_size, i.dim2_stride)],
                 iter=(i.iter_size, i.iter_stride), axcache=i.axcache,
                 next_bd=i.next_bd if i.use_next_bd else None)
    elif isinstance(i, WaitSyncInstr):
        d.update(col=i.col, row=i.row, channel=i.channel,
                 direction=i.direction)
    elif isinstance(i, PreemptInstr):
        d.update(level=i.level)
    return d


def load_buffer(path: str) -> bytes:
    """Read a raw transaction buffer ('-' = stdin)."""
    data = sys.stdin.buffer.read() if path == "-" else Path(path).read_bytes()
    return data


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Disassemble a raw XAIE transaction buffer "
                    "(little-endian uint32 words; '-' = stdin)")
    ap.add_argument("buffer", nargs="+",
                    help="raw instruction-buffer .bin (e.g. objdump-extracted "
                         "from an xrt_elf_*.elf captured by ff_instr_dump)")
    ap.add_argument("--no-header", action="store_true", dest="no_header",
                    help="stream has no 4-word FastFlowLM device header")
    ap.add_argument("--json", action="store_true",
                    help="machine-readable output (instructions + transfers)")
    ap.add_argument("--bd-groups", action="store_true",
                    help="also scan for DMA_BD_FENCE + 6 WRITE groups")
    args = ap.parse_args(argv)

    for path in args.buffer:
        data = load_buffer(path)
        if data[:4] == b"\x7fELF":
            print(f"[!] {path} is an ELF — extract the transaction section "
                  f"first, e.g.:\n"
                  f"    readelf -S {path}            # locate the instr section\n"
                  f"    objcopy -O binary --only-section=<sec> "
                  f"{path} buf.bin", file=sys.stderr)
            continue
        if len(data) % 4:
            print(f"[!] {path}: size {len(data)} not a multiple of 4; "
                  f"trailing bytes ignored", file=sys.stderr)

        parser = TxnParser(
            list(struct.unpack_from(f"<{len(data)//4}I", data)),
            header=not args.no_header)
        parser.parse()
        instrs = parser.instrs
        transfers = extract_dma_topology(instrs)
        groups = find_dma_bd_groups(instrs) if args.bd_groups else []

        if args.json:
            print(json.dumps({
                "file": path,
                "header": parser.header.__dict__ if parser.header else None,
                "num_instructions": len(instrs),
                "instructions": [_instr_to_dict(i) for i in instrs],
                "transfers": [
                    {"direction": t.direction, "arg_idx": t.arg_idx,
                     "arg_offset": t.arg_offset, "col": t.col,
                     "channel": t.channel, "bd_id": t.bd_id,
                     "buf_len_bytes": t.buf_len * 4,
                     "strides": t.strides}
                    for t in transfers],
                "bd_groups": [g.__dict__ for g in groups] if groups else [],
            }, indent=2))
        else:
            print(f"── {path}: {len(instrs)} instructions ──")
            if parser.header:
                print(f"header: {parser.header.describe()}")
            print(describe_all(instrs))
            print(f"\n── DMA transfers ({len(transfers)}) ──")
            for t in transfers:
                print(f"  {t.describe()}")
            if not transfers:
                print("  (no DDR_PATCH/SHIMDMA_BD pairs found)")
            if groups:
                print(f"\n── DMA BD groups ({len(groups)}) ──")
                for g in groups:
                    print(f"  {g.describe()}")

    return 0


if __name__ == "__main__":
    sys.exit(main())

